env:
  es2020: true
parserOptions:
  sourceType: 'module'
  parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - vue
extends:
  - plugin:vue/vue3-essential
  - eslint:recommended
  - '@vue/typescript/recommended'
  - prettier
